name: Build Commit

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      build-type:
        required: true
        type: string
      malloc-impl:
        required: true
        type: string
      prerelease:
        required: true
        type: string
      tooling:
        required: true
        type: string
      build-level:
        required: true
        type: string

jobs:
  HomestorePRBuild:
     uses: ./.github/workflows/build_dependencies.yml
     with:
       branch: ${{ github.ref }}
       platform: ${{ inputs.platform }}
       build-type: ${{ inputs.build-type }}
       malloc-impl: ${{ inputs.malloc-impl }}
       prerelease: ${{ inputs.prerelease }}
       tooling: ${{ inputs.tooling }}
       build-level: 'Testing'
     if: ${{ github.event_name == 'pull_request' }}

# jobs:
#   SislDeps:
#     uses: hkadayam/sisl/.github/workflows/build_dependencies.yml@master
#     with:
#       branch: master
#       platform: ${{ inputs.platform }}
#       build-type: ${{ inputs.build-type }}
#       malloc-impl: ${{ inputs.malloc-impl }}
#       prerelease: ${{ inputs.prerelease }}
#       tooling: None
#       build-level: 'Dependencies'

#   NuraftMesgDeps:
#     needs: SislDeps
#     uses: hkadayam/nuraft_mesg/.github/workflows/build_dependencies.yml@main
#     with:
#       branch: main
#       platform: ${{ inputs.platform }}
#       build-type: ${{ inputs.build-type }}
#       malloc-impl: ${{ inputs.malloc-impl }}
#       prerelease: ${{ inputs.prerelease }}
#       tooling: None
#       build-level: 'Dependencies'

#   IOMgrDeps:
#     needs: SislDeps
#     uses: hkadayam/iomanager/.github/workflows/build_dependencies.yml@master
#     with:
#       branch: master
#       platform: ${{ inputs.platform }}
#       build-type: ${{ inputs.build-type }}
#       malloc-impl: ${{ inputs.malloc-impl }}
#       prerelease: ${{ inputs.prerelease }}
#       tooling: None
#       build-level: 'Dependencies'

#   HomestoreCommitBuild:
#     needs: [IOMgrDeps, NuraftMesgDeps]
#     uses: ./.github/workflows/build_dependencies.yml
#     with:
#       branch: ${{ github.ref }}
#       platform: ${{ inputs.platform }}
#       build-type: ${{ inputs.build-type }}
#       malloc-impl: ${{ inputs.malloc-impl }}
#       prerelease: ${{ inputs.prerelease }}
#       tooling: ${{ inputs.tooling }}
#       build-level: 'Packaging'
#     if: ${{ github.event_name != 'pull_request' }}

#   HomestorePRBuild:
#     uses: ./.github/workflows/build_dependencies.yml
#     with:
#       branch: ${{ github.ref }}
#       platform: ${{ inputs.platform }}
#       build-type: ${{ inputs.build-type }}
#       malloc-impl: ${{ inputs.malloc-impl }}
#       prerelease: ${{ inputs.prerelease }}
#       tooling: ${{ inputs.tooling }}
#       build-level: 'Testing'
#     if: ${{ github.event_name == 'pull_request' }}
